name: Github Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Generate blog
      run: swift run Blog
    - name: Publish in github pages repo
      uses: crazy-max/ghaction-github-pages@v1.4.0
      with:
        repo: jomi86/Hvala
        target_branch: main
        keep_history: true
        allow_empty_commit: false
        build_dir: Output
        committer_name: jomi86
        commit_message: Update blog content
      env:
        GITHUB_PAT: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        
    - name: Add & Commit changes
      uses: EndBug/add-and-commit@v4.0.1
      with:
        author_name: jomi86
        message: Commit new output
